### PR TITLE
Fix single input AND gates

### PR DESCRIPTION
**Pull request by aayagzhov**
Hello! There is a problem of single input internal nodes in GraphML-files. For example in k2_orig:
BENCH (It is const 0 in AIG):
```
INPUT(pp)
...
pp_inv = NOT(pp)
...
new_n91_ = AND(pp,pp_inv)

```
But, after using andAIG2Graphml.py we get only one inverted edge:
```
    <node id="0">
      <data key="d0">pp</data>
      <data key="d1">0</data>
      <data key="d2">0</data>
    </node>
...
    <node id="45">
      <data key="d0">new_n91_</data>
      <data key="d1">2</data>
      <data key="d2">1</data>
    </node>
...
    <edge source="45" target="0">
      <data key="d3">1</data>
    </edge>

```
It should be:
```
    <node id="0">
      <data key="d0">pp</data>
      <data key="d1">0</data>
      <data key="d2">0</data>
    </node>
...
    <node id="45">
      <data key="d0">new_n91_</data>
      <data key="d1">2</data>
      <data key="d2">1</data>
    </node>
...
    <edge source="45" target="0">
      <data key="d3">0</data>
    </edge>
    <edge source="45" target="0">
      <data key="d3">1</data>
    </edge>
```
So, I suggest we use nx.MultiDiGraph in andAIG2Graphml.py to get two edges:
```
    <edge source="45" target="0" id="0">
      <data key="d3">0</data>
    </edge>
    <edge source="45" target="0" id="1">
      <data key="d3">1</data>
    </edge>
```
But, it will lead to appearance of edges idxs.

### CODE REVIEW

**Comment by animeshbchowdhury** [comment]
Hi @aayagzhov,

Are you saying that pp_inv node is not getting created? If pp_inv node is created, then it should have an arrow directed from pp_inv node to pp.

**Comment by aayagzhov** [comment]
Hi @animeshbchowdhury,

Sorry, no, I mean that the edge is missed. In GraphML-files "NOT" is set as the key of edges (inverted or not), so we need only one pp node. The new_n91_ node must have two inputs: pp and pp_inv, so we have two nodes (pp and new_n91_) and two edges (inverted and not inverted), like this:
```
    <node id="0">
      <data key="d0">pp</data>
      <data key="d1">0</data>
      <data key="d2">0</data>
    </node>
    <node id="45">
      <data key="d0">new_n91_</data>
      <data key="d1">2</data>
      <data key="d2">1</data>
    </node>
    <edge source="45" target="0">
      <data key="d3">0</data> <- not inverted
    </edge>
    <edge source="45" target="0">
      <data key="d3">1</data> <- inverted
    </edge>
```
But nx.DiGraph is used in andAIG2Graphml.py, and this type of graph don't see the difference between this edges and put only ONE inverted edge:
```
    <node id="0">
      <data key="d0">pp</data>
      <data key="d1">0</data>
      <data key="d2">0</data>
    </node>
    <node id="45">
      <data key="d0">new_n91_</data>
      <data key="d1">2</data>
      <data key="d2">1</data>
    </node>
    <edge source="45" target="0">
      <data key="d3">1</data> <- so, only one inverted edge(
    </edge>
```
This leads to the fact that new_n91_ node has only one input, that is not correct.

**Comment by animeshbchowdhury** [comment]
So, the AIG should look like this:

image

I expect the pp_inv node to be created, and there should be an edge from new_n91_ and one edge from pp_inv to pp. I do not expect two edges going from new_n91_ to pp.

**Comment by aayagzhov** [comment]
But, throw the script pp_inv node is not created.
I added log printing to the script:
```
def processANDAssignments(inputs,output,idxCounter,poList,nodeNameIDMapping,singleGateInputIOMapping,AIG_DAG):
    nType = nodeType["Internal"]
    nodeAttributedDict = {
        "node_id": output,
        "node_type": nType,
        "num_inverted_predecessors": 0
    }
    AIG_DAG.add_nodes_from([(idxCounter, nodeAttributedDict)])
    nodeNameIDMapping[output] = idxCounter
    numInvertedPredecessors = 0
    for inp in inputs:
        if not (inp in nodeNameIDMapping.keys()):
            srcIdx = nodeNameIDMapping[singleGateInputIOMapping[inp]] 
            eType = edgeType["NOT"]
            numInvertedPredecessors+=1
        else:
            srcIdx = nodeNameIDMapping[inp]
            eType = edgeType["BUFF"]
        ############LOG#################
        if idxCounter == 45:      <- LOG
            print(output)              <- LOG
            print(srcIdx, eType)  <- LOG
        #################################
        AIG_DAG.add_edge(idxCounter,srcIdx,edge_type=eType)
    AIG_DAG.nodes[idxCounter]["num_inverted_predecessors"] = numInvertedPredecessors

    # If output is primary output, add additional node to keep it consistent with POs having inverters
    if (output in poList):
        nType = nodeType["PO"]
        nodeAttributedDict = {
            "node_id": output+"_buff",
            "node_type": nType,
            "num_inverted_predecessors": 0
        }
        AIG_DAG.add_nodes_from([(idxCounter+1, nodeAttributedDict)])
        nodeNameIDMapping[output+"_buff"] = idxCounter+1
        srcIdx = idxCounter
        eType = edgeType["BUFF"]
        AIG_DAG.add_edge(idxCounter+1,srcIdx, edge_type=eType)

```

Then I run this script for k2_orif.bench, and for  new_n91_ node I have got:
```
new_n91_
0 0
new_n91_
0 1
```
So, throw thr script pp_inv node is not created, and there are two edges between pp node and new_n91_ node
Also, throw the script nodes for NOT are added, only when they are PO:
```
        elif line.__contains__("NOT"):
            line = line.replace(" ", "")
            output = re.search("(.*?)=", str(line)).group(1)
            inputPin = re.search("NOT\((.*?)\)", str(line)).group(1)
            singleInputgateIOMapping[output] = inputPin
            if output in poList:    <- but the pp_inv is not PO
                nodeAttributedDict = {
                    "node_id": output+"_inv",
                    "node_type": nodeType["PO"],
                    "num_inverted_predecessors": 1
                }
                AIG_DAG.add_nodes_from([(idxCounter, nodeAttributedDict)])
                nodeNameIDMapping[output+"_inv"] = idxCounter
                srcIdx = nodeNameIDMapping[inputPin]
                eType = edgeType["NOT"]
                AIG_DAG.add_edge(idxCounter, srcIdx, edge_type=eType)
                idxCounter += 1

``` 
pp_inv node is added to singleInputgateIOMapping as key with value pp, and the we coincide new_n91_ we have two edges from pp (inverted and not)

**Comment by animeshbchowdhury** [comment]
Hi @aayagzhov,

Makes sense. I'll review this but looks like your suggestion is correct and merge your PR. Thanks!

**Comment by aayagzhov** [comment]
Ok, thanks you!

**Review by animeshbchowdhury — APPROVED** [review]
There should be parallel edges (one original and one negated) from source to destination to represent constant-0 in AIG.

**Pull request merged**
